# BASE PATH
set(BASE_PATH ${CMAKE_CURRENT_SOURCE_DIR})
set(BUILD_PATH ${CMAKE_BINARY_DIR})
message(STATUS "BASE PATH:" ${BASE_PATH})

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BUILD_PATH}/../bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${BUILD_PATH}/../lib)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${BUILD_PATH}/../lib)
